version: '3.8'

services:
  mytonprovider:
    build: .
    container_name: myton-dev
    volumes:
      - ./db:/app/db
      - ./config:/app/config
    stdin_open: true
    tty: true
    restart: unless-stopped
